// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(voiidFFI)
import voiidFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_voiid_e2e_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_voiid_e2e_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureVoiidE2eCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * A device's MLS identity for groups (Phase 3).
 */
public protocol GroupMemberProtocol: AnyObject, Sendable {
    
    /**
     * Create a new group containing just this member.
     */
    func createGroup() throws  -> GroupSession
    
    /**
     * Join an existing group from a Welcome + ratchet tree.
     */
    func joinGroup(welcome: Data, ratchetTree: Data) throws  -> GroupSession
    
    /**
     * Public KeyPackage (TLS bytes) to upload so others can add us to groups.
     */
    func keyPackage() throws  -> Data
    
}
/**
 * A device's MLS identity for groups (Phase 3).
 */
open class GroupMember: GroupMemberProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_voiid_e2e_core_fn_clone_groupmember(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_voiid_e2e_core_fn_free_groupmember(handle, $0) }
    }

    
public static func create(identity: Data)throws  -> GroupMember  {
    return try  FfiConverterTypeGroupMember_lift(try rustCallWithError(FfiConverterTypeE2eFfiError_lift) {
    uniffi_voiid_e2e_core_fn_constructor_groupmember_create(
        FfiConverterData.lower(identity),$0
    )
})
}
    

    
    /**
     * Create a new group containing just this member.
     */
open func createGroup()throws  -> GroupSession  {
    return try  FfiConverterTypeGroupSession_lift(try rustCallWithError(FfiConverterTypeE2eFfiError_lift) {
    uniffi_voiid_e2e_core_fn_method_groupmember_create_group(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Join an existing group from a Welcome + ratchet tree.
     */
open func joinGroup(welcome: Data, ratchetTree: Data)throws  -> GroupSession  {
    return try  FfiConverterTypeGroupSession_lift(try rustCallWithError(FfiConverterTypeE2eFfiError_lift) {
    uniffi_voiid_e2e_core_fn_method_groupmember_join_group(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(welcome),
        FfiConverterData.lower(ratchetTree),$0
    )
})
}
    
    /**
     * Public KeyPackage (TLS bytes) to upload so others can add us to groups.
     */
open func keyPackage()throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeE2eFfiError_lift) {
    uniffi_voiid_e2e_core_fn_method_groupmember_key_package(
            self.uniffiCloneHandle(),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGroupMember: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = GroupMember

    public static func lift(_ handle: UInt64) throws -> GroupMember {
        return GroupMember(unsafeFromHandle: handle)
    }

    public static func lower(_ value: GroupMember) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GroupMember {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: GroupMember, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGroupMember_lift(_ handle: UInt64) throws -> GroupMember {
    return try FfiConverterTypeGroupMember.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGroupMember_lower(_ value: GroupMember) -> UInt64 {
    return FfiConverterTypeGroupMember.lower(value)
}






/**
 * Membership in one MLS group (Phase 3).
 */
public protocol GroupSessionProtocol: AnyObject, Sendable {
    
    /**
     * Add a member by their KeyPackage. Broadcast `commit` to existing members
     * and send `welcome`+`ratchet_tree` to the new member.
     */
    func addMember(member: GroupMember, theirKeyPackage: Data) throws  -> AddMemberOutput
    
    /**
     * Derive SRTP keys for a group call from the group's exporter secret.
     */
    func callKeys(member: GroupMember) throws  -> SrtpKeys
    
    /**
     * Process an incoming group message. Application messages return their
     * plaintext; commits/proposals are applied and return null.
     */
    func decrypt(member: GroupMember, message: Data) throws  -> Data?
    
    func encrypt(member: GroupMember, plaintext: Data) throws  -> Data
    
    /**
     * Current member count from our view of the group state.
     */
    func memberCount()  -> UInt32
    
    /**
     * Remove the member with stable identifier `identity`. Returns the commit
     * to broadcast to remaining members; rekeys so the removed member can't
     * read later messages.
     */
    func removeMember(member: GroupMember, identity: Data) throws  -> Data
    
}
/**
 * Membership in one MLS group (Phase 3).
 */
open class GroupSession: GroupSessionProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_voiid_e2e_core_fn_clone_groupsession(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_voiid_e2e_core_fn_free_groupsession(handle, $0) }
    }

    

    
    /**
     * Add a member by their KeyPackage. Broadcast `commit` to existing members
     * and send `welcome`+`ratchet_tree` to the new member.
     */
open func addMember(member: GroupMember, theirKeyPackage: Data)throws  -> AddMemberOutput  {
    return try  FfiConverterTypeAddMemberOutput_lift(try rustCallWithError(FfiConverterTypeE2eFfiError_lift) {
    uniffi_voiid_e2e_core_fn_method_groupsession_add_member(
            self.uniffiCloneHandle(),
        FfiConverterTypeGroupMember_lower(member),
        FfiConverterData.lower(theirKeyPackage),$0
    )
})
}
    
    /**
     * Derive SRTP keys for a group call from the group's exporter secret.
     */
open func callKeys(member: GroupMember)throws  -> SrtpKeys  {
    return try  FfiConverterTypeSrtpKeys_lift(try rustCallWithError(FfiConverterTypeE2eFfiError_lift) {
    uniffi_voiid_e2e_core_fn_method_groupsession_call_keys(
            self.uniffiCloneHandle(),
        FfiConverterTypeGroupMember_lower(member),$0
    )
})
}
    
    /**
     * Process an incoming group message. Application messages return their
     * plaintext; commits/proposals are applied and return null.
     */
open func decrypt(member: GroupMember, message: Data)throws  -> Data?  {
    return try  FfiConverterOptionData.lift(try rustCallWithError(FfiConverterTypeE2eFfiError_lift) {
    uniffi_voiid_e2e_core_fn_method_groupsession_decrypt(
            self.uniffiCloneHandle(),
        FfiConverterTypeGroupMember_lower(member),
        FfiConverterData.lower(message),$0
    )
})
}
    
open func encrypt(member: GroupMember, plaintext: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeE2eFfiError_lift) {
    uniffi_voiid_e2e_core_fn_method_groupsession_encrypt(
            self.uniffiCloneHandle(),
        FfiConverterTypeGroupMember_lower(member),
        FfiConverterData.lower(plaintext),$0
    )
})
}
    
    /**
     * Current member count from our view of the group state.
     */
open func memberCount() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_voiid_e2e_core_fn_method_groupsession_member_count(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Remove the member with stable identifier `identity`. Returns the commit
     * to broadcast to remaining members; rekeys so the removed member can't
     * read later messages.
     */
open func removeMember(member: GroupMember, identity: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeE2eFfiError_lift) {
    uniffi_voiid_e2e_core_fn_method_groupsession_remove_member(
            self.uniffiCloneHandle(),
        FfiConverterTypeGroupMember_lower(member),
        FfiConverterData.lower(identity),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeGroupSession: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = GroupSession

    public static func lift(_ handle: UInt64) throws -> GroupSession {
        return GroupSession(unsafeFromHandle: handle)
    }

    public static func lower(_ value: GroupSession) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> GroupSession {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: GroupSession, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGroupSession_lift(_ handle: UInt64) throws -> GroupSession {
    return try FfiConverterTypeGroupSession.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeGroupSession_lower(_ value: GroupSession) -> UInt64 {
    return FfiConverterTypeGroupSession.lower(value)
}






/**
 * A device's 1:1 identity (Phase 1).
 */
public protocol IdentityProtocol: AnyObject, Sendable {
    
    /**
     * Accept a 1:1 session from an inbound first message. Returns the new
     * session and the decrypted first plaintext.
     */
    func acceptSession(theirIdentityKey: String, firstMessage: WireMessage) throws  -> AcceptedSession
    
    /**
     * Stable Ed25519 fingerprint (base64) for safety-number verification.
     */
    func fingerprint()  -> String
    
    /**
     * Maximum one-time keys this device can hold at once.
     */
    func maxOneTimeKeys()  -> UInt32
    
    /**
     * Public bundle to upload so peers can start a session with us.
     */
    func publishBundle(oneTimeKeyCount: UInt32)  -> PublicBundle
    
    /**
     * Generate and publish additional one-time keys when supply runs low.
     * Returns only the new keys to upload.
     */
    func replenishPrekeys(count: UInt32)  -> PublicBundle
    
    /**
     * Start a 1:1 session as the sender of the first message.
     */
    func startSession(theirIdentityKey: String, theirOneTimeKey: String) throws  -> Session
    
    /**
     * Encrypted pickle to persist this identity in device storage.
     */
    func toPickle(pickleKey: Data) throws  -> String
    
}
/**
 * A device's 1:1 identity (Phase 1).
 */
open class Identity: IdentityProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_voiid_e2e_core_fn_clone_identity(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_voiid_e2e_core_fn_free_identity(handle, $0) }
    }

    
    /**
     * Generate a brand-new device identity.
     */
public static func create() -> Identity  {
    return try!  FfiConverterTypeIdentity_lift(try! rustCall() {
    uniffi_voiid_e2e_core_fn_constructor_identity_create($0
    )
})
}
    
    /**
     * Restore from an encrypted pickle saved in device storage.
     */
public static func restore(pickle: String, pickleKey: Data)throws  -> Identity  {
    return try  FfiConverterTypeIdentity_lift(try rustCallWithError(FfiConverterTypeE2eFfiError_lift) {
    uniffi_voiid_e2e_core_fn_constructor_identity_restore(
        FfiConverterString.lower(pickle),
        FfiConverterData.lower(pickleKey),$0
    )
})
}
    

    
    /**
     * Accept a 1:1 session from an inbound first message. Returns the new
     * session and the decrypted first plaintext.
     */
open func acceptSession(theirIdentityKey: String, firstMessage: WireMessage)throws  -> AcceptedSession  {
    return try  FfiConverterTypeAcceptedSession_lift(try rustCallWithError(FfiConverterTypeE2eFfiError_lift) {
    uniffi_voiid_e2e_core_fn_method_identity_accept_session(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(theirIdentityKey),
        FfiConverterTypeWireMessage_lower(firstMessage),$0
    )
})
}
    
    /**
     * Stable Ed25519 fingerprint (base64) for safety-number verification.
     */
open func fingerprint() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_voiid_e2e_core_fn_method_identity_fingerprint(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Maximum one-time keys this device can hold at once.
     */
open func maxOneTimeKeys() -> UInt32  {
    return try!  FfiConverterUInt32.lift(try! rustCall() {
    uniffi_voiid_e2e_core_fn_method_identity_max_one_time_keys(
            self.uniffiCloneHandle(),$0
    )
})
}
    
    /**
     * Public bundle to upload so peers can start a session with us.
     */
open func publishBundle(oneTimeKeyCount: UInt32) -> PublicBundle  {
    return try!  FfiConverterTypePublicBundle_lift(try! rustCall() {
    uniffi_voiid_e2e_core_fn_method_identity_publish_bundle(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(oneTimeKeyCount),$0
    )
})
}
    
    /**
     * Generate and publish additional one-time keys when supply runs low.
     * Returns only the new keys to upload.
     */
open func replenishPrekeys(count: UInt32) -> PublicBundle  {
    return try!  FfiConverterTypePublicBundle_lift(try! rustCall() {
    uniffi_voiid_e2e_core_fn_method_identity_replenish_prekeys(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(count),$0
    )
})
}
    
    /**
     * Start a 1:1 session as the sender of the first message.
     */
open func startSession(theirIdentityKey: String, theirOneTimeKey: String)throws  -> Session  {
    return try  FfiConverterTypeSession_lift(try rustCallWithError(FfiConverterTypeE2eFfiError_lift) {
    uniffi_voiid_e2e_core_fn_method_identity_start_session(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(theirIdentityKey),
        FfiConverterString.lower(theirOneTimeKey),$0
    )
})
}
    
    /**
     * Encrypted pickle to persist this identity in device storage.
     */
open func toPickle(pickleKey: Data)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeE2eFfiError_lift) {
    uniffi_voiid_e2e_core_fn_method_identity_to_pickle(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(pickleKey),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeIdentity: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Identity

    public static func lift(_ handle: UInt64) throws -> Identity {
        return Identity(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Identity) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Identity {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Identity, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIdentity_lift(_ handle: UInt64) throws -> Identity {
    return try FfiConverterTypeIdentity.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeIdentity_lower(_ value: Identity) -> UInt64 {
    return FfiConverterTypeIdentity.lower(value)
}






/**
 * An established 1:1 session (Phase 1).
 */
public protocol SessionProtocol: AnyObject, Sendable {
    
    func decrypt(message: WireMessage) throws  -> Data
    
    func encrypt(plaintext: Data) throws  -> WireMessage
    
    /**
     * Globally-unique session id (equal on both peers; matches the establishing
     * PreKey message's `prekey_session_id`). Used by clients to dedup candidate
     * sessions and avoid re-accepting a PreKey for a session they already hold.
     */
    func sessionId()  -> String
    
    func toPickle(pickleKey: Data) throws  -> String
    
}
/**
 * An established 1:1 session (Phase 1).
 */
open class Session: SessionProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_voiid_e2e_core_fn_clone_session(self.handle, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_voiid_e2e_core_fn_free_session(handle, $0) }
    }

    
public static func restore(pickle: String, pickleKey: Data)throws  -> Session  {
    return try  FfiConverterTypeSession_lift(try rustCallWithError(FfiConverterTypeE2eFfiError_lift) {
    uniffi_voiid_e2e_core_fn_constructor_session_restore(
        FfiConverterString.lower(pickle),
        FfiConverterData.lower(pickleKey),$0
    )
})
}
    

    
open func decrypt(message: WireMessage)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeE2eFfiError_lift) {
    uniffi_voiid_e2e_core_fn_method_session_decrypt(
            self.uniffiCloneHandle(),
        FfiConverterTypeWireMessage_lower(message),$0
    )
})
}
    
open func encrypt(plaintext: Data)throws  -> WireMessage  {
    return try  FfiConverterTypeWireMessage_lift(try rustCallWithError(FfiConverterTypeE2eFfiError_lift) {
    uniffi_voiid_e2e_core_fn_method_session_encrypt(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(plaintext),$0
    )
})
}
    
    /**
     * Globally-unique session id (equal on both peers; matches the establishing
     * PreKey message's `prekey_session_id`). Used by clients to dedup candidate
     * sessions and avoid re-accepting a PreKey for a session they already hold.
     */
open func sessionId() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_voiid_e2e_core_fn_method_session_session_id(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func toPickle(pickleKey: Data)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeE2eFfiError_lift) {
    uniffi_voiid_e2e_core_fn_method_session_to_pickle(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(pickleKey),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSession: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = Session

    public static func lift(_ handle: UInt64) throws -> Session {
        return Session(unsafeFromHandle: handle)
    }

    public static func lower(_ value: Session) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Session {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: Session, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSession_lift(_ handle: UInt64) throws -> Session {
    return try FfiConverterTypeSession.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSession_lower(_ value: Session) -> UInt64 {
    return FfiConverterTypeSession.lower(value)
}




/**
 * Result of accepting a session: the session plus the first message's bytes.
 */
public struct AcceptedSession {
    public var session: Session
    public var plaintext: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(session: Session, plaintext: Data) {
        self.session = session
        self.plaintext = plaintext
    }

    

    
}

#if compiler(>=6)
extension AcceptedSession: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAcceptedSession: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AcceptedSession {
        return
            try AcceptedSession(
                session: FfiConverterTypeSession.read(from: &buf), 
                plaintext: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: AcceptedSession, into buf: inout [UInt8]) {
        FfiConverterTypeSession.write(value.session, into: &buf)
        FfiConverterData.write(value.plaintext, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAcceptedSession_lift(_ buf: RustBuffer) throws -> AcceptedSession {
    return try FfiConverterTypeAcceptedSession.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAcceptedSession_lower(_ value: AcceptedSession) -> RustBuffer {
    return FfiConverterTypeAcceptedSession.lower(value)
}


/**
 * Bytes produced when adding a group member.
 */
public struct AddMemberOutput: Equatable, Hashable {
    public var commit: Data
    public var welcome: Data
    public var ratchetTree: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(commit: Data, welcome: Data, ratchetTree: Data) {
        self.commit = commit
        self.welcome = welcome
        self.ratchetTree = ratchetTree
    }

    

    
}

#if compiler(>=6)
extension AddMemberOutput: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAddMemberOutput: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AddMemberOutput {
        return
            try AddMemberOutput(
                commit: FfiConverterData.read(from: &buf), 
                welcome: FfiConverterData.read(from: &buf), 
                ratchetTree: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: AddMemberOutput, into buf: inout [UInt8]) {
        FfiConverterData.write(value.commit, into: &buf)
        FfiConverterData.write(value.welcome, into: &buf)
        FfiConverterData.write(value.ratchetTree, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAddMemberOutput_lift(_ buf: RustBuffer) throws -> AddMemberOutput {
    return try FfiConverterTypeAddMemberOutput.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAddMemberOutput_lower(_ value: AddMemberOutput) -> RustBuffer {
    return FfiConverterTypeAddMemberOutput.lower(value)
}


public struct CallSecret: Equatable, Hashable {
    public var secret: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(secret: String) {
        self.secret = secret
    }

    

    
}

#if compiler(>=6)
extension CallSecret: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCallSecret: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CallSecret {
        return
            try CallSecret(
                secret: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: CallSecret, into buf: inout [UInt8]) {
        FfiConverterString.write(value.secret, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCallSecret_lift(_ buf: RustBuffer) throws -> CallSecret {
    return try FfiConverterTypeCallSecret.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCallSecret_lower(_ value: CallSecret) -> RustBuffer {
    return FfiConverterTypeCallSecret.lower(value)
}


/**
 * Encrypting media returns the blob to upload + the key to send over a message.
 */
public struct EncryptedMedia: Equatable, Hashable {
    public var ciphertext: Data
    public var mediaKey: MediaKey

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(ciphertext: Data, mediaKey: MediaKey) {
        self.ciphertext = ciphertext
        self.mediaKey = mediaKey
    }

    

    
}

#if compiler(>=6)
extension EncryptedMedia: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEncryptedMedia: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EncryptedMedia {
        return
            try EncryptedMedia(
                ciphertext: FfiConverterData.read(from: &buf), 
                mediaKey: FfiConverterTypeMediaKey.read(from: &buf)
        )
    }

    public static func write(_ value: EncryptedMedia, into buf: inout [UInt8]) {
        FfiConverterData.write(value.ciphertext, into: &buf)
        FfiConverterTypeMediaKey.write(value.mediaKey, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptedMedia_lift(_ buf: RustBuffer) throws -> EncryptedMedia {
    return try FfiConverterTypeEncryptedMedia.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEncryptedMedia_lower(_ value: EncryptedMedia) -> RustBuffer {
    return FfiConverterTypeEncryptedMedia.lower(value)
}


public struct MediaKey: Equatable, Hashable {
    public var key: String
    public var nonce: String
    public var ciphertextSha256: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(key: String, nonce: String, ciphertextSha256: String) {
        self.key = key
        self.nonce = nonce
        self.ciphertextSha256 = ciphertextSha256
    }

    

    
}

#if compiler(>=6)
extension MediaKey: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMediaKey: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MediaKey {
        return
            try MediaKey(
                key: FfiConverterString.read(from: &buf), 
                nonce: FfiConverterString.read(from: &buf), 
                ciphertextSha256: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: MediaKey, into buf: inout [UInt8]) {
        FfiConverterString.write(value.key, into: &buf)
        FfiConverterString.write(value.nonce, into: &buf)
        FfiConverterString.write(value.ciphertextSha256, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMediaKey_lift(_ buf: RustBuffer) throws -> MediaKey {
    return try FfiConverterTypeMediaKey.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMediaKey_lower(_ value: MediaKey) -> RustBuffer {
    return FfiConverterTypeMediaKey.lower(value)
}


public struct PublicBundle: Equatable, Hashable {
    public var identityKey: String
    public var signingKey: String
    public var oneTimeKeys: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(identityKey: String, signingKey: String, oneTimeKeys: [String]) {
        self.identityKey = identityKey
        self.signingKey = signingKey
        self.oneTimeKeys = oneTimeKeys
    }

    

    
}

#if compiler(>=6)
extension PublicBundle: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypePublicBundle: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> PublicBundle {
        return
            try PublicBundle(
                identityKey: FfiConverterString.read(from: &buf), 
                signingKey: FfiConverterString.read(from: &buf), 
                oneTimeKeys: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: PublicBundle, into buf: inout [UInt8]) {
        FfiConverterString.write(value.identityKey, into: &buf)
        FfiConverterString.write(value.signingKey, into: &buf)
        FfiConverterSequenceString.write(value.oneTimeKeys, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePublicBundle_lift(_ buf: RustBuffer) throws -> PublicBundle {
    return try FfiConverterTypePublicBundle.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypePublicBundle_lower(_ value: PublicBundle) -> RustBuffer {
    return FfiConverterTypePublicBundle.lower(value)
}


public struct SrtpKeys: Equatable, Hashable {
    public var masterKey: Data
    public var masterSalt: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(masterKey: Data, masterSalt: Data) {
        self.masterKey = masterKey
        self.masterSalt = masterSalt
    }

    

    
}

#if compiler(>=6)
extension SrtpKeys: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSrtpKeys: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SrtpKeys {
        return
            try SrtpKeys(
                masterKey: FfiConverterData.read(from: &buf), 
                masterSalt: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: SrtpKeys, into buf: inout [UInt8]) {
        FfiConverterData.write(value.masterKey, into: &buf)
        FfiConverterData.write(value.masterSalt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSrtpKeys_lift(_ buf: RustBuffer) throws -> SrtpKeys {
    return try FfiConverterTypeSrtpKeys.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSrtpKeys_lower(_ value: SrtpKeys) -> RustBuffer {
    return FfiConverterTypeSrtpKeys.lower(value)
}


public struct WireMessage: Equatable, Hashable {
    public var msgType: UInt64
    public var body: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(msgType: UInt64, body: String) {
        self.msgType = msgType
        self.body = body
    }

    

    
}

#if compiler(>=6)
extension WireMessage: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWireMessage: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WireMessage {
        return
            try WireMessage(
                msgType: FfiConverterUInt64.read(from: &buf), 
                body: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: WireMessage, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.msgType, into: &buf)
        FfiConverterString.write(value.body, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWireMessage_lift(_ buf: RustBuffer) throws -> WireMessage {
    return try FfiConverterTypeWireMessage.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWireMessage_lower(_ value: WireMessage) -> RustBuffer {
    return FfiConverterTypeWireMessage.lower(value)
}


/**
 * Flat error surfaced to Swift/Kotlin. No secrets in any variant.
 */
public enum E2eFfiError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case NoSession
    case DecryptionFailed
    case InvalidKey
    case Serialization

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension E2eFfiError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeE2eFfiError: FfiConverterRustBuffer {
    typealias SwiftType = E2eFfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> E2eFfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .NoSession
        case 2: return .DecryptionFailed
        case 3: return .InvalidKey
        case 4: return .Serialization

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: E2eFfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .NoSession:
            writeInt(&buf, Int32(1))
        
        
        case .DecryptionFailed:
            writeInt(&buf, Int32(2))
        
        
        case .InvalidKey:
            writeInt(&buf, Int32(3))
        
        
        case .Serialization:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeE2eFfiError_lift(_ buf: RustBuffer) throws -> E2eFfiError {
    return try FfiConverterTypeE2eFfiError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeE2eFfiError_lower(_ value: E2eFfiError) -> RustBuffer {
    return FfiConverterTypeE2eFfiError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}
/**
 * Decrypt a downloaded blob using the media key received over a message.
 */
public func decryptMedia(mediaKey: MediaKey, ciphertext: Data)throws  -> Data  {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeE2eFfiError_lift) {
    uniffi_voiid_e2e_core_fn_func_decrypt_media(
        FfiConverterTypeMediaKey_lower(mediaKey),
        FfiConverterData.lower(ciphertext),$0
    )
})
}
/**
 * Encrypt an attachment. Upload `ciphertext`; send `media_key` over a message.
 */
public func encryptMedia(plaintext: Data)throws  -> EncryptedMedia  {
    return try  FfiConverterTypeEncryptedMedia_lift(try rustCallWithError(FfiConverterTypeE2eFfiError_lift) {
    uniffi_voiid_e2e_core_fn_func_encrypt_media(
        FfiConverterData.lower(plaintext),$0
    )
})
}
/**
 * Generate a fresh 1:1 call secret to send to the peer over a message.
 */
public func newCallSecret() -> CallSecret  {
    return try!  FfiConverterTypeCallSecret_lift(try! rustCall() {
    uniffi_voiid_e2e_core_fn_func_new_call_secret($0
    )
})
}
/**
 * The session id a PreKey (session-establishing) message would create, or `None`
 * for a Normal message. Equals the `Session::session_id()` of the matching session,
 * so a receiver can check "do I already have this session?" before accepting a new
 * one — avoiding a redundant accept that would consume another one-time key. Mirrors
 * libsignal's base-key dedup (`promote_matching_session`).
 */
public func prekeySessionId(message: WireMessage) -> String?  {
    return try!  FfiConverterOptionString.lift(try! rustCall() {
    uniffi_voiid_e2e_core_fn_func_prekey_session_id(
        FfiConverterTypeWireMessage_lower(message),$0
    )
})
}
/**
 * Compute the safety number two users compare out-of-band (anti-MITM). Pass
 * each party's stable identifier plus their fingerprint.
 */
public func safetyNumber(ourId: Data, ourFingerprint: String, theirId: Data, theirFingerprint: String) -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_voiid_e2e_core_fn_func_safety_number(
        FfiConverterData.lower(ourId),
        FfiConverterString.lower(ourFingerprint),
        FfiConverterData.lower(theirId),
        FfiConverterString.lower(theirFingerprint),$0
    )
})
}
/**
 * Derive SRTP keys for a 1:1 call from the exchanged call secret.
 */
public func srtpKeysFor1to1(callSecret: CallSecret)throws  -> SrtpKeys  {
    return try  FfiConverterTypeSrtpKeys_lift(try rustCallWithError(FfiConverterTypeE2eFfiError_lift) {
    uniffi_voiid_e2e_core_fn_func_srtp_keys_for_1to1(
        FfiConverterTypeCallSecret_lower(callSecret),$0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_voiid_e2e_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_func_decrypt_media() != 49753) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_func_encrypt_media() != 14634) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_func_new_call_secret() != 50736) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_func_prekey_session_id() != 3026) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_func_safety_number() != 42464) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_func_srtp_keys_for_1to1() != 18645) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_method_groupmember_create_group() != 5804) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_method_groupmember_join_group() != 25991) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_method_groupmember_key_package() != 50506) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_method_groupsession_add_member() != 4832) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_method_groupsession_call_keys() != 45542) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_method_groupsession_decrypt() != 37682) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_method_groupsession_encrypt() != 61784) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_method_groupsession_member_count() != 21166) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_method_groupsession_remove_member() != 56234) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_method_identity_accept_session() != 45680) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_method_identity_fingerprint() != 42725) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_method_identity_max_one_time_keys() != 39892) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_method_identity_publish_bundle() != 65256) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_method_identity_replenish_prekeys() != 4485) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_method_identity_start_session() != 41300) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_method_identity_to_pickle() != 25643) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_method_session_decrypt() != 32319) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_method_session_encrypt() != 1186) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_method_session_session_id() != 32195) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_method_session_to_pickle() != 19437) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_constructor_groupmember_create() != 17051) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_constructor_identity_create() != 24981) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_constructor_identity_restore() != 11926) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_voiid_e2e_core_checksum_constructor_session_restore() != 28494) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureVoiidE2eCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all