#!/usr/bin/env node
//
// Generates components/dots.ts — the dotted world grid, each dot tagged with the region it
// falls in, at BUILD TIME.
//
// The look is Aceternity's world-map (dotted-map under the hood). The component itself is
// not usable here: it draws animated arcs between point PAIRS and has no concept of filling
// a country by value, it needs Tailwind + next-themes + motion (this panel is plain CSS),
// and it renders the grid as one flat <img> data-URI that cannot be coloured per region.
//
// So the library is used directly and the classification is done here: every land dot is
// point-in-polygon tested against the same Natural Earth geometry the choropleth already
// uses, including the Indian official J&K boundary. The result is the dotted aesthetic with
// real per-region colour — which the upstream component cannot do.
//
import { writeFileSync, readFileSync } from 'node:fs';
import DottedMapImport from 'dotted-map';
import { feature } from 'topojson-client';

const DottedMap = DottedMapImport.default ?? DottedMapImport;

const GRID_H = 60;
const map = new DottedMap({ height: GRID_H, grid: 'diagonal' });
const points = map.getPoints();
const svg = map.getSVG({ radius: 0.22, color: '#000', shape: 'circle', backgroundColor: 'transparent' });
const [, , VB_W, VB_H] = svg.match(/viewBox="([^"]+)"/)[1].split(' ').map(Number);

// dotted-map lays its grid over a full-world equirectangular, so the inverse is linear.
const toLon = (x) => (x / VB_W) * 360 - 180;
const toLat = (y) => 90 - (y / VB_H) * 180;

const topo = JSON.parse(readFileSync(
  new URL('../../../node_modules/world-atlas/countries-50m.json', import.meta.url), 'utf8'));
const fc = feature(topo, topo.objects.countries);

const REGION = JSON.parse(readFileSync(new URL('./regions.json', import.meta.url), 'utf8'));

// India's official boundary, same outline the choropleth uses. See build-land.mjs for why
// this is here: Natural Earth stops India at 35.5°N and Indian law requires otherwise.
const JK_CLAIMED = [
  [74.0, 32.5], [73.9, 33.2], [74.2, 34.0], [73.8, 34.6], [74.3, 35.2],
  [74.6, 35.9], [75.2, 36.4], [75.9, 36.7], [76.6, 36.9], [77.4, 37.0],
  [78.2, 36.8], [78.9, 36.2], [79.5, 35.6], [80.0, 35.0], [80.3, 34.4],
  [79.8, 34.0], [79.2, 33.5], [78.6, 33.0], [78.2, 32.6], [77.6, 32.4],
  [76.8, 32.3], [76.0, 32.2], [75.2, 32.2], [74.6, 32.3], [74.0, 32.5],
];

/** Ray casting. Rings here are small and the test runs once at build time. */
function inRing(lon, lat, ring) {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i], [xj, yj] = ring[j];
    if ((yi > lat) !== (yj > lat) && lon < ((xj - xi) * (lat - yi)) / (yj - yi) + xi) {
      inside = !inside;
    }
  }
  return inside;
}

function inGeom(lon, lat, geom) {
  const polys = geom.type === 'Polygon' ? [geom.coordinates] : geom.coordinates;
  for (const poly of polys) {
    // First ring is the outer boundary; the rest are holes.
    if (!inRing(lon, lat, poly[0])) continue;
    let hole = false;
    for (let i = 1; i < poly.length; i++) if (inRing(lon, lat, poly[i])) { hole = true; break; }
    if (!hole) return true;
  }
  return false;
}

// Bounding boxes first: 3065 dots against 240 countries is 735k polygon tests otherwise.
const candidates = fc.features
  .filter((f) => REGION[String(f.id)])
  .map((f) => {
    const polys = f.geometry.type === 'Polygon' ? [f.geometry.coordinates] : f.geometry.coordinates;
    const all = polys.flat().flat();
    const lons = all.map((c) => c[0]), lats = all.map((c) => c[1]);
    return {
      region: REGION[String(f.id)],
      geom: f.geometry,
      bb: [Math.min(...lons), Math.min(...lats), Math.max(...lons), Math.max(...lats)],
    };
  });

const jkBB = [73.8, 32.2, 80.3, 37.0];

const dots = [];
for (const p of points) {
  const lon = toLon(p.x), lat = toLat(p.y);
  let region = '';
  // J&K is tested FIRST, so a dot inside the claimed boundary is India even where Natural
  // Earth assigns it to Pakistan or China. Same precedence the choropleth gets from paint
  // order.
  if (lon >= jkBB[0] && lon <= jkBB[2] && lat >= jkBB[1] && lat <= jkBB[3]
      && inRing(lon, lat, JK_CLAIMED)) {
    region = 'India';
  } else {
    for (const c of candidates) {
      if (lon < c.bb[0] || lon > c.bb[2] || lat < c.bb[1] || lat > c.bb[3]) continue;
      if (inGeom(lon, lat, c.geom)) { region = c.region; break; }
    }
  }
  dots.push([Math.round(p.x * 10) / 10, Math.round(p.y * 10) / 10, region]);
}

const regions = [...new Set(dots.map((d) => d[2]).filter(Boolean))].sort();
const out = `// GENERATED by scripts/build-dots.mjs. Do not edit — re-run the script.
//
// The dotted world grid (dotted-map), with every land dot tagged by the region it falls in,
// resolved at build time against Natural Earth geometry plus India's official J&K boundary.
export const DOT_VB_W = ${VB_W};
export const DOT_VB_H = ${VB_H};
/** [x, y, region] — region is '' for land with no mapping. */
export const DOTS: [number, number, string][] = ${JSON.stringify(dots)};
`;

writeFileSync(new URL('../components/dots.ts', import.meta.url), out);
const tagged = dots.filter((d) => d[2]).length;
console.log(`dots: ${dots.length}  tagged: ${tagged}  regions: ${regions.length}  KB: ${(out.length / 1024).toFixed(0)}`);
console.log(`India dots: ${dots.filter((d) => d[2] === 'India').length}`);
