-- 052_game_lobbies.sql — the party lobby: ready-states, a join code, and lobby chat.
--
-- ── WHY THIS EXISTS ─────────────────────────────────────────────────────────────
-- Voiid's match flow today is an INVITE AND WAIT: create a match with a list of
-- player ids, everyone sits at `status = 'waiting'`, and the match flips to `active`
-- when the last seat fills. That is enough for a 1:1 duel and it is what
-- `GameLobbyView` renders.
--
-- The designed lobby is a different thing. It has members who are visibly READY or
-- not, a join code you can hand to someone outside the invite list, and a chat while
-- you wait. None of that can be derived from `game_matches.player_ids`, which knows
-- only who is in the seat list — not whether they are looking at the screen, not what
-- they typed, and not how a stranger might arrive.
--
-- ── WHY NOT JUST WIDEN game_matches ─────────────────────────────────────────────
-- 024_games.sql chose a jsonb `player_ids` array over a join table with an explicit
-- rationale: matches are read whole, always, and 2-4 players made a join table three
-- extra queries for no benefit. That reasoning still holds FOR THE MATCH.
--
-- A lobby is the opposite shape. Its rows change independently and often (a ready
-- toggle, a mic toggle, someone leaving), and a chat is unbounded. Cramming per-member
-- mutable state into a jsonb blob means every ready-up is a read-modify-write of the
-- whole array, with the lost-update race that implies when four people tap at once.
-- So: a real table, one row per member, updated in place.
--
-- ── THE LOBBY IS NOT E2EE, AND SAYS SO ──────────────────────────────────────────
-- Lobby chat is SERVER-READABLE. That is a deliberate, scoped exception in the same
-- spirit as 030_communities.sql, and the reasons are specific:
--
--   * A lobby is ephemeral and disposable — it exists for the minutes before a match
--     and is deleted with it. There is no history to protect because there is no
--     history.
--   * Members can arrive by JOIN CODE, i.e. people you have never messaged and hold no
--     ratchet session with. Establishing a Double Ratchet per lobby joiner, for a chat
--     that dies in four minutes, is a key-exchange cost with no lasting benefit.
--   * The content is "ready?" and "one sec" — coordination, not correspondence.
--
-- MESSAGES, CALLS, MOMENTS, MAP PRESENCE AND BACKUPS ARE UNAFFECTED and remain
-- end-to-end encrypted. Nothing here is a precedent for weakening any of them. If
-- lobby chat ever becomes durable, this decision must be revisited — durability is
-- exactly what makes plaintext dangerous.

-- ─────────────────────────────────────────────────────────────────────────────────
-- The lobby itself
--
-- One row per match that has a lobby. Not every match does: a bot practice game or a
-- rematch has nothing to coordinate, so the row is created only when a lobby is opened.
-- ─────────────────────────────────────────────────────────────────────────────────
create table if not exists game_lobbies (
    -- Shares the match's id rather than minting its own. A match has at most one lobby,
    -- and keying them together means "the lobby for this match" is never a lookup.
    match_id     uuid primary key references game_matches(id) on delete cascade,

    host_user_id uuid not null references users(id) on delete cascade,

    -- ── THE JOIN CODE ───────────────────────────────────────────────────────────
    -- Short, human-shareable, and the ONE way into a lobby you were not invited to.
    -- Unique while the lobby is open (see the partial index), reusable afterwards —
    -- codes are a small space and permanently burning them would exhaust it.
    --
    -- Generated by the route, not here: a default would tie the alphabet to a
    -- migration. The route excludes visually ambiguous characters (0/O, 1/I/L).
    join_code    text,
    -- Whether the code works at all. A private lobby is invite-only regardless of who
    -- knows the code — the flag is checked first, so revoking access is one update.
    is_public    boolean not null default false,

    -- Host-set options the reference exposes. Free text rather than enums: these are
    -- product vocabulary that changes more often than a schema should, and the client
    -- is the authority on what it offers.
    format       text,
    -- Fill empty seats with bots when the countdown ends, rather than blocking on a
    -- seat nobody claimed.
    fill_empty   boolean not null default false,

    created_at   timestamptz not null default now(),
    -- Set when the host starts the match. A lobby past this point is read-only history
    -- for the seconds before it is cascaded away with the match.
    started_at   timestamptz,

    constraint game_lobbies_join_code_shape
        check (join_code is null or join_code ~ '^[A-Z0-9]{4,8}$')
);

-- A join code resolves to at most ONE open lobby. Partial on `started_at` so a started
-- lobby releases its code back into the pool immediately.
create unique index if not exists game_lobbies_open_code_idx
    on game_lobbies (join_code)
    where join_code is not null and started_at is null;

-- ─────────────────────────────────────────────────────────────────────────────────
-- Who is in the lobby, and are they ready
--
-- Distinct from `game_matches.player_ids`. That array is the SEAT LIST — who the match
-- belongs to. This table is PRESENCE IN THE LOBBY — who currently has it open. The two
-- diverge constantly: an invited player who has not opened the app is in `player_ids`
-- and not here, and someone browsing via join code is here before they are seated.
-- ─────────────────────────────────────────────────────────────────────────────────
create table if not exists game_lobby_members (
    match_id   uuid not null references game_lobbies(match_id) on delete cascade,
    user_id    uuid not null references users(id) on delete cascade,

    -- waiting | ready. Not an enum type: a third state (away? spectating?) should be a
    -- one-line change, not a `ALTER TYPE` that locks the table.
    state      text not null default 'waiting',

    -- The reference draws a mic glyph per member. It is a LOBBY-LOCAL intent flag —
    -- there is no voice transport behind it yet, and the client must not present it as
    -- live audio until there is. Stored so the intent survives a reconnect.
    mic_on     boolean not null default true,

    -- Which seat they took, when the game cares (Ludo's four colours). Null for games
    -- where a seat is just a slot.
    seat       int,

    joined_at  timestamptz not null default now(),
    -- Heartbeat. A member whose lobby was killed by iOS never sends a leave, so the
    -- client treats a stale row as gone and a sweeper can reap it.
    seen_at    timestamptz not null default now(),

    primary key (match_id, user_id),

    constraint game_lobby_members_state
        check (state in ('waiting', 'ready'))
);

-- The lobby's own render: everyone in this lobby, in arrival order.
create index if not exists game_lobby_members_lobby_idx
    on game_lobby_members (match_id, joined_at);

-- "Am I in a lobby?" — for restoring the screen after a cold start.
create index if not exists game_lobby_members_user_idx
    on game_lobby_members (user_id);

-- One seat per person per lobby, and no two people in the same seat.
create unique index if not exists game_lobby_members_seat_idx
    on game_lobby_members (match_id, seat)
    where seat is not null;

-- ─────────────────────────────────────────────────────────────────────────────────
-- Lobby chat
--
-- SERVER-READABLE — see the header. Deliberately minimal: no edits, no reactions, no
-- replies, no attachments. It exists to say "ready?" before a match starts.
-- ─────────────────────────────────────────────────────────────────────────────────
create table if not exists game_lobby_messages (
    id         bigserial primary key,
    match_id   uuid not null references game_lobbies(match_id) on delete cascade,
    -- ON DELETE SET NULL, not CASCADE: deleting an account must not silently rewrite a
    -- conversation other people were part of. A null author renders as "Left".
    user_id    uuid references users(id) on delete set null,

    body       text not null,
    created_at timestamptz not null default now(),

    -- Short on purpose. This is coordination, and a 4000-character essay in a lobby
    -- chat is a misuse of the surface rather than a use of it.
    constraint game_lobby_messages_len check (char_length(body) between 1 and 500)
);

-- The only query: this lobby's messages, oldest first. bigserial ordering is the send
-- order, which is what a chat needs — `created_at` can tie at millisecond resolution.
create index if not exists game_lobby_messages_lobby_idx
    on game_lobby_messages (match_id, id);
