-- Official status is assigned by the controlled reset/bootstrap operation only.
-- Public community creation/PATCH deliberately cannot write this column.
alter table communities add column if not exists official_key text;
alter table communities add column if not exists posting_policy text not null default 'members';
alter table communities add constraint communities_official_key_check
  check (official_key is null or official_key in ('jobs', 'feedback', 'updates'));
alter table communities add constraint communities_posting_policy_check
  check (posting_policy in ('members', 'managers'));
create unique index if not exists communities_official_key_unique
  on communities (official_key) where official_key is not null;

-- One MLS coordinator per Space prevents two owner devices creating unrelated groups.
-- A revoked/lost coordinator is never silently replaced: that would fork existing keys.
alter table community_channels add column if not exists mls_coordinator_device_id uuid references devices(id) on delete set null;
alter table community_channels add column if not exists mls_group_id text;
create table if not exists community_mls_batches (
  id uuid primary key,
  conversation_id uuid not null references conversations(id) on delete cascade,
  sender_device_id uuid not null references devices(id) on delete cascade,
  created_at timestamptz not null default now()
);

-- Timestamp ties occur for all MLS events written in a transaction. Preserve commit order.
alter table mls_group_events add column if not exists sequence bigint generated by default as identity;
create unique index if not exists mls_group_events_sequence on mls_group_events(sequence);
