import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {fileURLToPath} from 'node:url';
import vm from 'node:vm';
import ts from 'typescript';
import pg from 'pg';
const url=process.env.FINANCE_TEST_DATABASE_URL;
test('admission: concurrent scans, current roles, cancellation, refunds and nonce rotation',{skip:!url},async()=>{
 assert.match(new URL(url!).pathname,/finance_test$/);
 const pool=new pg.Pool({connectionString:url});
 const schema=`admission_${Date.now()}`;
 const setup=await pool.connect();
 const q=async(s:string,p?:unknown[])=>(await setup.query(s,p)).rows;
 await q(`create schema ${schema};set search_path to ${schema}`);
 try{
 await q(`create table communities(id text primary key,owner_id text,suspended_at timestamptz);
 create table community_members(community_id text,user_id text,role text,state text);
 create table community_events(id text primary key,community_id text,status text,suspended_at timestamptz);
 create table event_orders(id text primary key,status text,quantity integer default 1,admission_mode text default 'individual');
 create table event_tickets(id text primary key,event_id text,order_id text,holder_id text,state text,qr_nonce text,checked_in_at timestamptz,checked_in_by text);
 create table event_staff(event_id text,user_id text,role text,state text,expires_at timestamptz);
 create table users(id text primary key,full_name text,username text,phone text);
 insert into communities values('c','host',null);
 insert into community_members values('c','host','owner','active'),('c','member','member','active');
 insert into community_events values('e','c','published',null);
 insert into event_orders(id,status) values('o','paid');
 insert into event_tickets values('t','e','o','guest','valid','nonce',null,null);
 insert into users values('guest','Guest','guest_name','must-not-leak');`);
 const exports:any={};
 const transaction=async(fn:Function)=>{const c=await pool.connect();try{await c.query('begin');await c.query(`set local search_path to ${schema}`);const r=await fn(async(s:string,p?:unknown[])=>(await c.query(s,p)).rows);await c.query('commit');return r;}catch(e){await c.query('rollback');throw e;}finally{c.release();}};
 vm.runInNewContext(ts.transpileModule(readFileSync(fileURLToPath(new URL('../src/payments/admission.ts',import.meta.url)),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,{exports,require:()=>({withTransaction:transaction})});
 const admit=(user='host',nonce='nonce')=>exports.admitTicket('e','t',nonce,user);
 assert.equal((await admit('member')).reason,'access_removed');
 assert.equal((await admit('host','old')).reason,'superseded');
 const results=await Promise.all([admit(),admit()]);
 assert.equal(results.filter(r=>r.ok).length,1);
 const duplicate=results.find(r=>!r.ok);assert.equal(duplicate.reason,'already_checked_in');assert.ok(duplicate.checked_in_at);
 assert.ok(!JSON.stringify(results).includes('must-not-leak'));
 await q('update event_tickets set checked_in_at=null,checked_in_by=null');
 await q("update community_events set status='cancelled'");assert.equal((await admit()).reason,'event_unavailable');
 await q("update community_events set status='published',suspended_at=now()");assert.equal((await admit()).reason,'event_unavailable');
 await q('update community_events set suspended_at=null');
 await q("update community_members set state='left' where user_id='host'");assert.equal((await admit()).reason,'access_removed');
 await q("update community_members set state='active' where user_id='host'");
 await q("update event_orders set status='refunded'");assert.equal((await admit()).reason,'unpaid');
 await q("update event_orders set status='paid';update event_tickets set state='void'");assert.equal((await admit()).reason,'void');
 assert.equal((await q('select checked_in_at from event_tickets'))[0].checked_in_at,null);
 await q("update event_tickets set state='valid';insert into event_staff values('e','member','volunteer','active',now()+interval '1 day')");
 const volunteer=await admit('member');assert.equal(volunteer.ok,true);
 await q("update event_tickets set checked_in_at=null,checked_in_by=null;update event_staff set state='revoked'");
 assert.equal((await admit('member')).reason,'access_removed');
 await q("update event_staff set state='active',expires_at=now()-interval '1 second'");
 assert.equal((await admit('member')).reason,'access_removed');

 await q("update event_orders set quantity=10,admission_mode='group';update event_staff set state='active',expires_at=now()+interval '1 day'");
 for(let i=1;i<10;i++)await q("insert into event_tickets values($1,'e','o','guest','valid',$2,null,null)",['t'+i,'n'+i]);
 assert.equal((await admit()).reason,'group_code_required');
 const group=()=>exports.admitTicket('e','t','nonce','host',true);
 assert.equal((await exports.admitTicket('e','t1','n1','host',true)).reason,'group_unavailable');
 const groups=await Promise.all([group(),group()]);
 assert.equal(groups.filter(x=>x.ok).length,1);
 assert.equal(groups.find(x=>x.ok).people,10);
 assert.equal((await q('select count(*)::int as n from event_tickets where checked_in_at is not null'))[0].n,10);
 assert.ok(!JSON.stringify(groups).includes('guest_name'));
 await q("update event_tickets set checked_in_at=null,checked_in_by=null;update event_tickets set qr_nonce='rotated' where id='t'");
 assert.equal((await group()).reason,'superseded');
 await q("update event_tickets set qr_nonce='nonce' where id='t';update event_orders set status='refunded'");
 assert.equal((await group()).reason,'unpaid');

 }finally{await q(`drop schema ${schema} cascade`);setup.release();await pool.end();}
});
