'use client';
import { useCallback, useEffect, useState } from 'react';
import { api } from '../../../lib/api';
type Total = { currency:string;status:string;orders:number;tickets:string;gross_minor:string;commission_minor:string|null;organiser_minor:string|null;unpriced_orders:number };
type Order = { id:string;event_title:string;status:string;quantity:number;currency:string;amount_minor:string;commission_bps:number|null;commission_minor:string|null;organiser_minor:string|null;created_at:string;checked_in:number };
type Data = {community:{name:string;event_commission_bps:number};totals:Total[];orders:Order[];has_more:boolean;events:{id:string;title:string;status:string;starts_at:string;orders:number;checked_in:number}[];events_truncated:boolean;history:{created_at:string;admin_email:string;detail:{previous_bps:number;commission_bps:number;reason:string}}[]};
function money(v:string|null,c:string){if(v===null)return 'Not recorded';const n=BigInt(v);return `${c} ${n/100n}.${(n%100n).toString().padStart(2,'0')}`;}
export default function FinancePanel({id}:{id:string}){
 const [data,setData]=useState<Data|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[rate,setRate]=useState('25'),[reason,setReason]=useState(''),[offset,setOffset]=useState(0),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{setBusy(true);try{const d=await api<Data>(`/communities/${id}/finance?offset=${offset}`);setData(d);setRate(String(d.community.event_commission_bps/100));setError('');}catch(e){setData(null);setError(e instanceof Error?e.message:'Unable to load finance');}finally{setBusy(false);}},[id,offset]);
 useEffect(()=>{void load();},[load]);
 async function save(){if(!data)return;setBusy(true);setError('');setNotice('');try{if(!/^\d{1,3}(\.\d{1,2})?$/.test(rate)||Number(rate)>100)throw Error('Enter a percentage from 0 to 100, with at most two decimal places.');await api(`/communities/${id}/commission`,{method:'PATCH',json:{commission_bps:Math.round(Number(rate)*100),expected_bps:data.community.event_commission_bps,reason}});await load();setReason('');setNotice('Commission saved for new orders. Existing orders retain their recorded rate.');}catch(e){setError(e instanceof Error?e.message:'Unable to save');}finally{setBusy(false);}}
 return <section className="card" style={{marginBottom:24}}><h2>Event finance</h2><p className="muted">Default Voiid commission: 25%. Amounts below are order records before processing fees and taxes. They are not bank balances.</p>
 {error&&<p role="alert" className="notice error">{error}</p>}{notice&&<p role="status">{notice}</p>}<button disabled={busy} onClick={()=>void load()}>{busy?'Loading…':'Refresh'}</button>
 {data&&<><fieldset disabled={busy}><legend>Community commission override</legend><label>Voiid commission (%)<input type="number" min="0" max="100" step="0.01" value={rate} onChange={e=>setRate(e.target.value)}/></label><label>Reason (recorded in audit history)<input maxLength={500} value={reason} onChange={e=>setReason(e.target.value)}/></label><p>Applies to new orders across this community. Previous sales are unchanged.</p><button disabled={reason.trim().length<5} onClick={()=>void save()}>Save commission</button></fieldset>
 <h3>Sales by currency and order status</h3><div style={{overflowX:'auto'}}><table><thead><tr><th>Currency / status</th><th>Orders / places</th><th>Gross</th><th>Voiid commission</th><th>Organiser share</th></tr></thead><tbody>{data.totals.map(t=><tr key={t.currency+t.status}><td>{t.currency} · {t.status}{t.unpriced_orders>0&&<p>{t.unpriced_orders} older orders have no commission snapshot</p>}</td><td>{t.orders} / {t.tickets}</td><td>{money(t.gross_minor,t.currency)}</td><td>{money(t.commission_minor,t.currency)}</td><td>{money(t.organiser_minor,t.currency)}</td></tr>)}</tbody></table></div>{data.totals.length===0&&<p>No event orders yet.</p>}
 <h3>Settlement and refunds</h3><p>Route settlement tracking is not connected. No withdrawable balance is available. Refunded order statuses require provider reconciliation before being treated as completed bank refunds.</p>
 <h3>Events</h3>{data.events.length===0&&<p>No events yet.</p>}{data.events.map(e=><p key={e.id}><strong>{e.title}</strong> · {e.status} · {new Date(e.starts_at).toLocaleString()} · {e.orders} orders · {e.checked_in} admitted</p>)}{data.events_truncated&&<p>Showing the latest 100 events.</p>}
 <h3>Order breakdown</h3><div style={{overflowX:'auto'}}><table><thead><tr><th>Order / event</th><th>Created</th><th>Status / quantity</th><th>Gross</th><th>Commission</th><th>Organiser share</th><th>Admitted</th></tr></thead><tbody>{data.orders.map(o=><tr key={o.id}><td>{o.event_title}<br/><small>{o.id}</small></td><td>{new Date(o.created_at).toLocaleString()}</td><td>{o.status} / {o.quantity}</td><td>{money(o.amount_minor,o.currency)}</td><td>{o.commission_bps===null?'Not recorded':`${o.commission_bps/100}%`} · {money(o.commission_minor,o.currency)}</td><td>{money(o.organiser_minor,o.currency)}</td><td>{o.checked_in}</td></tr>)}</tbody></table></div><button disabled={busy||offset===0} onClick={()=>setOffset(Math.max(0,offset-50))}>Previous</button><span> Page {offset/50+1} </span><button disabled={busy||!data.has_more} onClick={()=>setOffset(offset+50)}>Next</button>
 <h3>Recent commission changes</h3>{data.history.length===0&&<p>No overrides recorded.</p>}{data.history.map((h,i)=><p key={i}>{new Date(h.created_at).toLocaleString()} · {h.admin_email} · {h.detail.previous_bps/100}% → {h.detail.commission_bps/100}% · {h.detail.reason}</p>)}</>}
 </section>;
}
